#****************************************************************************
#
# Makefile for Kyra.
# Lee Thomason
# www.grinninglizard.com
#
# This is a GNU make (gmake) makefile
#****************************************************************************

# DEBUG can be set to YES to include debugging info, or NO otherwise
DEBUG          := NO

# PROFILE can be set to YES to include profiling info, or NO otherwise
PROFILE        := NO

#****************************************************************************

ifeq (RELEASE, ${MAKE_KYRA})
	DEBUG   := NO
	PROFILE := NO
endif

ifeq (DEBUG, ${MAKE_KYRA})
	DEBUG   := YES
	PROFILE := NO
endif

ifeq (PROFILE, ${MAKE_KYRA})
	DEBUG   := NO
	PROFILE := YES
endif

CC     := gcc
CXX    := g++
LD     := g++
AR     := ar rc
RANLIB := ranlib

DEBUG_CFLAGS     := -Wall -Wno-unknown-pragmas -Wno-format -g -DDEBUG
RELEASE_CFLAGS   := -Wall -Wno-unknown-pragmas -Wno-format -O3

LIBS		 :=

DEBUG_CXXFLAGS   := ${DEBUG_CFLAGS}
RELEASE_CXXFLAGS := ${RELEASE_CFLAGS}

DEBUG_LDFLAGS    := -g -shared
RELEASE_LDFLAGS  := -shared

ifeq (YES, ${DEBUG})
   CFLAGS       := ${DEBUG_CFLAGS}
   CXXFLAGS     := ${DEBUG_CXXFLAGS}
   LDFLAGS      := ${DEBUG_LDFLAGS}
else
   CFLAGS       := ${RELEASE_CFLAGS}
   CXXFLAGS     := ${RELEASE_CXXFLAGS}
   LDFLAGS      := ${RELEASE_LDFLAGS}
endif

ifeq (YES, ${PROFILE})
   CFLAGS   := ${CFLAGS} -pg
   CXXFLAGS := ${CXXFLAGS} -pg
   LDFLAGS  := ${LDFLAGS} -pg
endif

#****************************************************************************
# Preprocessor directives
#****************************************************************************

ifeq (YES, ${PROFILE})
  DEFS :=
else
  DEFS :=
endif

#****************************************************************************
# Include paths
#****************************************************************************

INCS := $(shell sdl-config --cflags)


#****************************************************************************
# Makefile code common to all platforms
#****************************************************************************

CFLAGS   := ${CFLAGS}   ${DEFS}
CXXFLAGS := ${CXXFLAGS} ${DEFS}

#****************************************************************************
# Targets of the build
#****************************************************************************

OUTPUT := libkyra.a

all: ${OUTPUT}
#	 cp krengine.la /usr/lib/libkrengine.la


#****************************************************************************
# Source files
#****************************************************************************

SRCS := action.cpp \
		box.cpp \
		boxresource.cpp \
		canvas.cpp \
		canvasresource.cpp \
		color.cpp \
		dirtyrectangle.cpp \
		encoder.cpp \
		engine.cpp \
		fontresource.cpp \
		krmath.cpp \
		image.cpp \
		imagetree.cpp \
		imnode.cpp \
		kyraresource.cpp \
		painter.cpp \
		parser.cpp \
		pixelblock.cpp \
		rle.cpp \
		sdlutil.cpp \
		sprite.cpp \
		spriteresource.cpp \
		textbox.cpp \
		tile.cpp \
		tileresource.cpp \
		vault.cpp \
        namefield.cpp \
		../util/glmap.cpp \
		../util/glrandom.cpp \
		../util/glstring.cpp \
		../util/gldebug.cpp \
		../util/glmemorypool.cpp \
        ../util/glisomath.cpp \
        ../util/glperformance.cpp \
        ../util/glgraph.cpp \
        ../util/glprime.cpp \
		../gui/console.cpp


# Add on the sources for libraries
SRCS := ${SRCS}

OBJS := $(addsuffix .o,$(basename ${SRCS}))


#****************************************************************************
# Output
#****************************************************************************

#${OUTPUT}: ${OBJS}
#	${LD} -o $@ ${LDFLAGS} ${OBJS} ${LIBS} ${EXTRA_LIBS}
${OUTPUT}: ${OBJS}
	${AR} ${OUTPUT} ${OBJS}

#****************************************************************************
# common rules
#****************************************************************************

# Rules for compiling source files to object files
%.o : %.cpp
	${CXX} -c ${CXXFLAGS} ${INCS} $< -o $@

%.o : %.c
	${CC} -c ${CFLAGS} ${INCS} $< -o $@

clean:
	-rm -f core ${OBJS} ${OUTPUT}

depend:
	makedepend -Y ${SRCS} ${INCS}

install: ${OUTPUT}
	mkdir -p /usr/local/Kyra/lib ; \
	install -m755 libkyra.a /usr/local/lib ; \
	mkdir -p /usr/local/include/Kyra/engine ; \
	install -m755 *.h /usr/local/include/Kyra/engine
