=head1 NAME

brainblast - Brainblast a puzzle memory game.

=head1 SYNOPSIS

brainblast

=head1 DESCRIPTION

The goal of the game is to remember a pattern and then
rebuild it from pieces that are falling from the sky.
You can play alone with a friend or against the computer.

=head2 Theese are the keys used:

=over 4

=item C<F>

Enter or leave full screen mode.

=item C<M>

Toggle the background music.

=item C<ESC>

Abort or exit current game.

=item Keys for player 1

Uses C<UP>, C<DOWN>, C<LEFT>, C<RIGHT> for navigation. C<R-CTRL> for jumping and C<R-SHIFT> for placing pieces in the puzzle.

=item Keys for player 2

Uses C<W>, C<S>, C<A>, C<D> for navigation. C<L-CTRL> for jumping and C<L-SHIFT> for placing pieces in the puzzle.

=back

=head1 FILES

Files created by brainblast. For files accessed, see the installed files.

=over 4

=item F<~/.brainblast_score>

The highscore table

=back

=head1 HOMEPAGE

L<http://brainblast.sourceforge.net/>

=head1 AUTHOR

Daniel Bengtsson <daniel@bengtssons.info>
