#!/bin/sh

prefix=/usr/local
exec_prefix=${prefix}
exec_prefix_set=no

usage="\
Usage: kyra-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 2.1.3
      ;;
    --libs)
      echo -lkyra -L/usr/lib -L/usr/local/lib -L/usr/X11R6/lib  -lSDL -lpthread -lSDL_image -L${exec_prefix}/lib
      ;; 
    --cflags)
      if test ${prefix}/include != /usr/include ; then
          # Handle oddities in Win32 path handling (assumes prefix)
          prefix=`echo ${prefix} | sed 's,^//\([A-Z]\),\1:,'`

          includes=-I${prefix}/include
      fi
      echo $includes -I${prefix}/include/Kyra -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
